site_name: Picovico
site_description: Static content pages
repo_url: https://github.com/picovico/picovico.github.io
pages:
  - ['index.md', 'Home']
  - ['faq.html.md', 'FAQ']
  - ['privacy.html.md', 'Privacy Policy']
  - ['terms.html.md', 'Terms & Conditions']
  - ['mohars.html.md', 'Mohars']
docs_dir: 'content'
site_dir: 'build'
theme: readthedocs
